import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contentful</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}
